language: cpp

compiler:
  - clang
  - gcc

before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX

     
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
      - boost-latest
    packages:
      - libboost1.55-all-dev
      - cmake-data
      - cmake

script: cmake . && make
